services:
    tahoe_multi_tenancy.tenant_aware_subscriber:
        class: Tahoe\Bundle\MultiTenancyBundle\EventSubscriber\TenantAwareSubscriber
        arguments: ["@service_container"]
        tags:
            - { name: doctrine.event_subscriber }
